### ISSUE TITLE
Create installation instructions from GitHub

### ISSUE THREAD

**Issue by 4D44H** [4D44H/lara-vedst#29]
ToDo:
- check if homestead is an option
- create short installation instructions from git (for testing and development)

**Comment by 4D44H** [comment]
*Test version for windows xampp*
```"$>" stands for console commands (Start --> run --> cmd)```
 
**Initial installations:**
1. install xampp - https://www.apachefriends.org/index.html
2. install composer - https://getcomposer.org/Composer-Setup.exe
3. install git - https://windows.github.com/
4. install Laravel 5.0 to folder /xampp/htdocs/lara-vedst - http://laravel.com/docs/5.0/installation

*At this point you should be able to see Laravel 5 initial page here http://127.0.0.1/lara-vedst/public/*

**Lara-vedst installation:**
5. copy all files from 4D44H/lara-vedst to /xampp/htdocs/lara-vedst, overwriting the original laravel files
6. ```$> cd c:/xampp/htdocs/lara-vedst```
7. ```$> composer install```
8.

**Comment by bobcanthelpyou** [comment]
@4D44H could there be a possibility to fetch lara-vedst also via composer and use laravel only out of the 'vendor/laravel/laravel' folder?

**Comment by 4D44H** [comment]
@bobcanthelpyou yep, working on it now.
I'm currently migrating to laravel 5, will finish today. Stay tuned.

**Comment by 4D44H** [comment]
**Installing using XAMPP on Windows:**
```"$>" stands for console commands (Start --> run --> cmd)```
 
**Initial installations:**
1. Install XAMPP - https://www.apachefriends.org/index.html
2. Install Composer - https://getcomposer.org/Composer-Setup.exe
3. Install git - https://windows.github.com/
4. Copy all files from 4D44H/lara-vedst to *C:/xampp/htdocs/lara-vedst*
5. Open project directory in the console - ```$> cd c:/xampp/htdocs/lara-vedst``` and update dependencies - ```$> composer update```
6. Create a new MySQL database named "lara-vedst" in XAMPP (e.g. by using http://127.0.0.1/phpmyadmin ) and update database schema - ```$> php artisan migrate```
7. In the Apache Server config (httpd.conf) change ```DocumentRoot "C:/xampp/htdocs``` to ```DocumentRoot "C:/xampp/htdocs/lara-vedst/public"``` to hide "/lara-vedst/public" path.

*At this point you should be able to run Lara VedSt without error here: http://127.0.0.1/ or http://localhost*

**Comment by 4D44H** [comment]
**Installing on a CentOS production server**
```"$>" stands for console commands```

1. Install the server, e.g.: ```$> yum install httpd mariadb-server php php-ldap php-mysql```

2. Install Composer: 
  - open directory: ```$> cd /usr/local/bin/ ```
  - download composer: ```$> php -r "readfile('https://getcomposer.org/installer');" | php``` 
  - add a symbolic link: ```$> ln –s /usr/local/bin/composer.phar /usr/local/bin/composer```.

3. Install git: ```$> yum install git```

4. Copy lara-vedst files with git:
  - open directory: ```$> cd /var/www/```
  - clone repository with git: ```$> git clone https://github.com/4D44H/lara-vedst.git ```

5. Update dependencies: ```$> composer update``` 
*(this one can take some time - don't worry, make some tea)*

6. Change permissions: 
  - ```$> cd /var/www```
  - ```$> chown -R apache:apache lara-vedst/```
  - ```$> chmod -R 755 lara-vedst/```
  - ```$> chmod -R 777 lara-vedst/storage```

7. To hide "/lara-vedst/public" path:
  - open the Apache Server config (*actual filename may vary*): ```$> vi /etc/httpd/conf.d/laravel.conf```
  - type ```i``` to enter editing mode
  - change ```DocumentRoot to ```DocumentRoot "var/www/lara-vedst/public"```: ```$> cd /var/www```
  - hit ```<ESC>``` to exit editing mode
  - type ```:x``` and hit ```<Return>``` to exit *vi*

7. Restart the server: ```$> /etc/init.d/httpd restart```

8. Create a MySQL database named "lara-vedst":
  - switch to MySQL: ```$> mysql –u root –p```
  - create new database named "lara-vedst": ```$> create database lara-vedst```
  - update database schema from /lara-vedst folder: ```$> php artisan migrate```

9. Edit environment variables in the file ```.env``` located in ```/var/www/lara-vedst/```:
  - set "APP_ENV=production"
  - set "APP_DEBUG=false" 
  - enter new random key to "APP_KEY=" (32 signs)
  - set "DB_HOST", "DB_DATABASE", "DB_USERNAME" and "DB_PASSWORD" to your database credentials

10. For development purposes a workaround is built into the LoginController which assigns a random dummy-user at each login event, ignoring login/password input from user. Change it to the your actual authentification routine.

*At this point you should be able to run Lara VedSt.*

**Comment by 4D44H** [comment]
P.S. installation via composer & packagist should be possible, yet I will try it later.
