### ISSUE TITLE
Add "contact admin" field to footer

### ISSUE THREAD

**Issue by 4D44H** [4D44H/lara-vedst#38]
For change requests and error messages.

**Comment by bobcanthelpyou** [comment]
It could be also a 'report a problem' link to the issues here: https://github.com/4D44H/lara-vedst/issues

But the reporters need a GitHub account, if they avoid to create an account they couldn't report a problem.

If the bug reporters use the issue tracker it might be easier for the developers

**Comment by 4D44H** [comment]
No need for now, decided to stick to email instead.
