### ISSUE TITLE
Old IE support

### ISSUE THREAD

**Issue by 4D44H** [4D44H/lara-vedst#8]
Current status:
- in Internet Explorer <8 navigation isn't shown

ToDo:
- add IE support

**Comment by 4D44H** [comment]
Use HTML5 Shiv.

**Comment by bobcanthelpyou** [comment]
https://en.wikipedia.org/wiki/HTML5_Shiv

https://github.com/aFarkas/html5shiv

**Comment by 4D44H** [comment]
HTML5shiv was added, but doesn't solve the problem - the issue is within bootstrap navbar styles. Common fixes for the boostrap issue didn't help much..
Closed because issue importance <= zero, no known usage of IE10-- for half a year.
