### ISSUE TITLE
development environment in vagrant

### ISSUE THREAD

**Issue by ThomDietrich** [4D44H/lara-vedst#88]
Hey,
this is another way to get a development environment or rather a deployment solution.
A virtual machine managed by Vagrant: https://github.com/ThomDietrich/homestead-lara-vedst

**Comment by ThomDietrich** [comment]
Benefits? We'll see ;)

**Comment by ThomDietrich** [comment]
How about closing this ticket and putting the link into README.md ?

**Comment by 4D44H** [comment]
Done, see https://github.com/4D44H/lara-vedst/wiki/Installation-in-a-virtual-machine-(Windows,-Linux,-OSX)
