### ISSUE TITLE
auth via database as alternative to LDAP

### ISSUE THREAD

**Issue by ThomDietrich** [4D44H/lara-vedst#90]
aimed at development/testing environments and installations without LDAP server.

* [ ] additional database table for user authentication (userID, hash, group etc.)
* [ ] options to activate/deactivate database auth or LDAP auth in app config files
* [ ] default demo users in the seeder data can replace the random auth currently in loginController
* [ ] auth table will replace the special LDAP-OVERWRITE user in loginController

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
@4D44H any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by ThomDietrich** [comment]
any preferences or ideas on columns besides the obvious counterparts to the ldap fields?

**Comment by 4D44H** [comment]
nope, looks good. but use #3 issue instead, closing this one.
Have a look at "service providers" - could be a clean solution.
