### ISSUE TITLE
It's not possible to add a comment when the shift is already taken.

### ISSUE THREAD

**Issue by bedo2991** [4D44H/lara-vedst#91]
To add a comment, it is now necessary to delete the current entry and add it again with the comment.

**Comment by 4D44H** [comment]
Totally an implementation error in current version (branch "master"), thanks for reporting!
Yet I have already fixed it in [lara-2.0-beta branch](/4D44H/lara-vedst/tree/lara-2.0-beta), see [ScheduleEntryController@update](https://github.com/4D44H/lara-vedst/blob/lara-2.0-beta/app/Http/Controllers/ScheduleEntryController.php) lines 173-279, where we separate comments from name+club and process them separately, allowing to coment changes on empty entries and without changing a name first, therefore closing the ticket.
