### ISSUE TITLE
(Security) Stricter control for guests changing members

### ISSUE THREAD

**Issue by 4D44H** [4D44H/lara-vedst#92]
Multiple issues of a bot changing a member entry by adding same authenticated user and an arbitrary comment. See event id 358 as an example.
Exact string is a garbage string with a website address, e.g. "St7Mjw http://www dot FyLitCl7----DELETED-BY-ME----axTXbj5iNG.com", but always the same address with a changing string in front of it.
If username field is empty, usually "mark" was added there and a random string to the club field.

ToDo:
- clean the DB _(done)_
- find how it was possible, fix the code _(done)_
- prevent further spamming - maybe a blacklist for specific comment types and/or IPs? _(honeypot implemented, robots.txt changed, blacklist/ip filters - in discussion)_
- propagate changes to lara-2.0-beta branch _(done)_
- add comment logging to revision log _(done)_

**Comment by ThomDietrich** [comment]
In terms of spam in general:
It would be an idea to block non-german IP addresses on web server side (as long as the user base is mainly restricted to Ilmenau). Have done it on my private website after I realized that 80% of my devoted visitors were from China or the US ;)
Alternative: introduce blacklists (e.g. https://github.com/Stevie-Ray/apache-nginx-referral-spam-blacklist).

**Comment by 4D44H** [comment]
We'll discuss it with club management and admins, could be a solution, thanks!
